#!/usr/bin/env python3
"""
Batch-generate TTS samples for a set of voices using tts_chatgpt.py.

Writes outputs to tts/<voice>_tts_output.mp3 (by default) for each voice in VOICES.
"""

import subprocess
from pathlib import Path

# VOICES = ["alloy", "echo", "fable", "onyx", "nova", "shimmer"]
VOICES = ['alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer', 'coral', 'verse', 'ballad', 'ash', 'sage', 'marin', 'cedar']
TEXT = "This is a sample vocal exercise generated by ChatGPT text to speech."
MODEL = "gpt-4o-mini-tts"


def main():
    root = Path(__file__).resolve().parent
    tts_dir = root / "tts"
    tts_dir.mkdir(exist_ok=True)
    script = root / "tts_chatgpt.py"

    for voice in VOICES:
        out_path = tts_dir / f"{voice}_tts_output.mp3"
        cmd = [
            "python3",
            str(script),
            "--voice",
            voice,
            "--text",
            TEXT,
            "--model",
            MODEL,
            "--output",
            str(out_path),
        ]
        print(f"Generating TTS for voice '{voice}' -> {out_path}")
        subprocess.run(cmd, check=True)


if __name__ == "__main__":
    main()
